changelog:
  exclude:
    labels:
      - ignore-for-release
    authors:
      - dependabot
  categories:
    - title: "✨ What's New"
      labels:
        - enhancement
        - feature
    - title: "🐛 Bug Fixes"
      labels:
        - bug
        - fix
    - title: "⚡ Performance"
      labels:
        - performance
    - title: "🔧 Maintenance"
      labels:
        - chore
        - dependencies
        - refactor
